spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sampleDB
    username: sampleDB
    password: sampleDB
    driver-class-name: org.postgresql.Driver

  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false